version: '3.3'
services:
  backend:
    build:
      context: ./backend
      args:
        INSTALL_DEV: ${INSTALL_DEV-true}
        INSTALL_JUPYTER: ${INSTALL_JUPYTER-true}
    command: /start-reload.sh
    environment:
      - 'JUPYTER=jupyter notebook --ip=0.0.0.0 --allow-root'
      - SERVER_NAME=${DOMAIN}
      - SERVER_HOST=http://${DOMAIN}
    networks:
      default:
        aliases:
          - ${DOMAIN}
    ports:
      - '8888:8888'
    volumes:
      - ./backend/app:/app
  frontend:
    build:
      context: ./frontend
    environment:
      - SERVER_HOST=http://${DOMAIN}
    ports:
      - '5555:5555'
  db:
    ports:
      - '5432:5432'
  proxy:
    ports:
      - '80:80'
    volumes:
      - './nginx.template:/etc/nginx/conf.d/default.conf:ro'
